# Generated by Django 3.2.8 on 2022-04-16 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='prduct',
            new_name='product',
        ),
    ]
